### ISSUE TITLE
What is the model of your x86 synology?

### ISSUE THREAD

**Issue by ShagoY** [runfalk/synology-wireguard#1] opened 2019-03-20 11:59 UTC
Hello,
I just saw that you modified the makefile for x86, can you tell me what the model of your Synology is?
Thank.

**Comment by runfalk** [comment] 2019-03-20 16:15
Hi, I have the DS218j which runs a dual core ARM processor. I modified the Makefile because I saw this fork: https://github.com/raman325/synology-wireguard/commit/aca61074a08e3b88dadc98c3630929d07ed99378. It changed my hardcoded ARM values to other values hardcoded for X86.

The original Makefile only worked when compiling on X86 systems and if your NAS had an ARM processor.

The changes I made to the Makefile theoretically allow you to compile on any platform supported by the Synology toolchain. You should also be able to target all Synology NAS architectures. Since I only have the DS218j I can't say whether other models work or not.

The compiling is done on your desktop/laptop in a Docker container.

**Comment by ShagoY** [comment] 2019-03-21 12:12
Sorry.... Obviously I wanted to ask @raman325 because I have an "Apollolake" synology (DS918+).

Thanks to your link to the akhener guide, I managed to create the module + exec of Wireguard. 
But I am also interested in creating a SPK.

I discovered your git on Reddit, thanks again for your work!

Well now I'm trying to prevent Synology from running all the traffic on Wireguard but that's another story ;-)

**Comment by raman325** [comment] 2019-03-21 15:26
@runfalk I was planning to look at how to do the same so that I could contribute back but you beat me to it. Thanks for putting this together!

**Comment by runfalk** [comment] 2019-03-21 15:51
Thank you @raman325!

If you get errors about memneq already being defined, look at my answer for #2. I have no idea which CPUs that have this and which that do not.

I'll reopen this issue until I hear back from you.

**Comment by raman325** [comment] 2019-03-21 18:36
The updated Makefile worked (DS1817+, DSM6.2, Avoton family) and I did not get any errors related to memneq, so it's definitely not based on x86 vs ARM.

To make this whole process simpler, have you considered turning it into a Dockerfile with a volume that could be host mounted to grab the packaged outputs? Something like this (untested, and I created a root directory where all the operations would take place)

```dockerfile
FROM ubuntu

ENV PACKAGE_ARCH avoton
ENV DSM_VER 6.2

RUN apt-get update \
 && apt-get -qy install git python3 wget ca-certificates \
 && mkdir -p /build/source

WORKDIR /build

VOLUME /build/result_spk

ENTRYPOINT exec bash -c "git clone https://github.com/SynologyOpenSource/pkgscripts-ng \
 && git clone https://github.com/runfalk/synology-wireguard source/WireGuard \
 && pkgscripts-ng/EnvDeploy -p $PACKAGE_ARCH -v $DSM_VER \
 && cp /etc/ssl/certs/ca-certificates.crt build_env/*/etc/ssl/certs/ \
 && pkgscripts-ng/PkgCreate.py -p $PACKAGE_ARCH -v $DSM_VER -S --build-opt=-J --print-log -c WireGuard"
```

Assuming the dockerfile works (and if it doesn't, it probably just needs some minor tweaks),  your instructions would basically be two lines after downloading the Dockerfile:
```bash
sudo docker build -t synobuild .
sudo docker run --rm --privileged --name synobuild --env DSM_VER=<DSM Version> --env PACKAGE_ARCH=<Use value from here: https://www.synology.com/en-global/knowledgebase/DSM/tutorial/Compatibility_Peripherals/What_kind_of_CPU_does_my_NAS_have>  -v .:/build/result_spk synobuild
```

**Comment by runfalk** [comment] 2019-03-22 10:36
Thank you! I'll go ahead and add your dockerfile to the project. I may even be able to get automatic builds going.

Did the resulting package work for you? Could I add your model to the compatibility table?

**Comment by molgar** [comment] 2019-03-22 13:54
Hi. For what it's worth I compiled succesfully for the DS713, DSM 6.2. It's cedarview running on an Intel Atom.

**Comment by runfalk** [comment] 2019-03-22 14:05
@molgar did you successfully use the package as well?

**Comment by molgar** [comment] 2019-03-22 14:14
> 
> 
> @molgar did you successfully use the package as well?

Yes I did. I am having trouble getting to route traffic to the wan on the VPN server end, but I suspect that may be a networking issue.

**Comment by ShagoY** [comment] 2019-03-22 14:28
Hi @runfalk 

Your new "Compiling" section lacks information on how to create the "synobuild" container.
For example, should we create it from the Dockerfile provided by @raman325 or should we clone your git?
And why not provide the image directly on "docker hub"?
Personally, I have the knowledge to build images but I'm not sure everyone knows how to do it ;-)

Thank you again!

**Comment by runfalk** [comment] 2019-03-22 14:36
Hey @ShagoY,

There are instructions on how to make the Docker image:

> I've used docker to compile everything, as pkgscripts-ng clutters the file system quite a bit. First create a docker image by running the following command in this repository:
> 
> `sudo docker build -t synobuild .`

Then you use the run command to create a temporary build container from that image. I'll add the `git clone` command to be more explicit about it.

I won't add it to DockerHub because I have no use for that. If anyone else wants to add it, feel free to so.

**Comment by raman325** [comment] 2019-03-22 16:35
@runfalk yes I am actively using the package I built using your instructions 😄 and to reiterate, I did NOT test the Dockerfile I proposed above, I just think it's very close to completion since it's mostly just a copy and paste from your README

**Comment by runfalk** [comment] 2019-03-22 17:03
@raman325 I added your model to the compatibility table.

I've added SPKs for all platforms that have been confirmed to work. See the release page: https://github.com/runfalk/synology-wireguard/releases

**Comment by runfalk** [comment] 2019-03-22 17:19
I think every issue in here has been resolved, so I'm closing the ticket.

**Closed by runfalk** 2019-03-22 17:19 UTC

**Comment by runfalk** [comment] 2019-03-23 15:24
For those of you who want to use the NAS as a gateway. I've updated the release with `iptables` support:

https://github.com/runfalk/synology-wireguard/releases/tag/0.0.20190227-2

Check the README for an example.
