### ISSUE TITLE
Data not transfering through when used as client

### ISSUE THREAD

**Issue by kharveys** [runfalk/synology-wireguard#15] opened 2019-06-11 21:05 UTC
For my use case I want to use my NAS (216j) as an client to an existing wireguard server so I can use Download Station with the wireguard VPN. However I can't seem to get it working. When doing ```wg-quick up wg0``` I get no error messages and starts up fine. Using ```wg show``` it shows it is connected but in the transfer tab it shows that almost no data has been fed trough it. When using an IPmagnet to see what IP my nas uses when downloading a torrent it shows my own IP and not the one I'm supposedly connected to. I also tried Deluge instead of Download Station but nothing changes. 

My wg0.conf is as follow:

```
[Interface]
Address = 10.200.200.6/24
PrivateKey = [privatekey]


[Peer]
PublicKey = [publickey]
AllowedIPs = 10.0.0.0/24
Endpoint = [server-ip]
PersistentKeepalive = 25
```

I first wanted to use ```AllowedIPs = 0.0.0.0/0``` to route all my network through the VPN, this works on my desktop and phone, but it gave my the following error: ```Error: argument "suppress_prefixlength" is wrong: Failed to parse rule type```

Any ideas how to get this working?

**Comment by runfalk** [comment] 2019-06-11 21:13
I think this is directly related to #10. Can you verify your Synology DSM version?

**Comment by kharveys** [comment] 2019-06-11 21:16
It's the same version so I guess it's the same problem, any idea why this is happening?

**Comment by runfalk** [comment] 2019-06-11 21:18
Nope, if I did I would have fixed it. Sadly I haven't had time to investigate it properly. If someone could contact Synology's support about it that would be great.

**Comment by runfalk** [comment] 2019-07-16 13:24
I'll close this since it's a duplicate of #10.

**Closed by runfalk** 2019-07-16 13:24 UTC
